export const TRAINS_LIST_LOADED = "TRAINS_LIST_LOADED";
export const STATIONS_LIST_LOADED = "STATIONS_LIST_LOADED";
export const FROM_STATION = "FROM_STATION";
export const TO_STATION = "TO_STATION";
export const ACTIVE_CONTENT_INDEX = "ACTIVE_CONTENT_INDEX";
export const DATE_OF_JOURNEY = "DATE_OF_JOURNEY";
export const LOAD_SRC_TO_DEST_TRAINS = "LOAD_SRC_TO_DEST_TRAINS";
export const CHANGE_LOAD_TYPE = "CHANGE_LOAD_TYPE";